apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            ["sh", "-c", "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;"]
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command:
            ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;"]
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/flight_booking
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: PAYMENT_WINDOW_MINUTES
              value: "15"
            - name: LOG_LEVEL
              value: info
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: booking-service
